export {LayoutInfo,
  UserInfo,
  PersonalInfo,
  ProfileSummaryInfo,
  SkillsInfo,
  EducationInfo,
  ProjectsInfo,
  WorkexpInfo,
  AchievementsInfo,
  HobbiesInfo,
  AreaOfIntrestInfo} from './ResumeComponents';