export {
  UserName,
  UserDesignation,
  UserPhoto,
  LeftBlockHeading,
  LeftBlockContactInfo,
  LeftBlockBullet,
  LeftBlockSkill,
  VL,
  RightBlockHeading,
  RightBlockLogo,
  RightBlockProject,
  RightBlockWorkExp,
  RightBlockEdu,
  RightBlockBullet,
  RightBlockBulletSmall,
  RightBlockArea,
  BlockProject,
  BlockBullet,
  BlockBulletSmall,
  BlockEdu,
  LeftBlock,
  RightBlock,
  HiddenTextElement,
  MainBlock,
  ResumeWrapper
} from './LegacyResumeComponents';